//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.26 at 11:56:06 PM MSK 
//


package com.example.cash;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.cash package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.cash
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateRequest }
     * 
     */
    public CreateRequest createCreateRequest() {
        return new CreateRequest();
    }

    /**
     * Create an instance of {@link CreateResponse }
     * 
     */
    public CreateResponse createCreateResponse() {
        return new CreateResponse();
    }

    /**
     * Create an instance of {@link CreateResponse.Return }
     * 
     */
    public CreateResponse.Return createCreateResponseReturn() {
        return new CreateResponse.Return();
    }

    /**
     * Create an instance of {@link CreateRequest.Request }
     * 
     */
    public CreateRequest.Request createCreateRequestRequest() {
        return new CreateRequest.Request();
    }

    /**
     * Create an instance of {@link CreateRequest.Request.OperationEntity }
     * 
     */
    public CreateRequest.Request.OperationEntity createCreateRequestRequestOperationEntity() {
        return new CreateRequest.Request.OperationEntity();
    }

    /**
     * Create an instance of {@link CreateRequest.Request.OperationEntity.Documents }
     * 
     */
    public CreateRequest.Request.OperationEntity.Documents createCreateRequestRequestOperationEntityDocuments() {
        return new CreateRequest.Request.OperationEntity.Documents();
    }

    /**
     * Create an instance of {@link CreateRequest.Request.OperationEntity.Documents.CashSymbols }
     * 
     */
    public CreateRequest.Request.OperationEntity.Documents.CashSymbols createCreateRequestRequestOperationEntityDocumentsCashSymbols() {
        return new CreateRequest.Request.OperationEntity.Documents.CashSymbols();
    }

    /**
     * Create an instance of {@link CreateResponse.Return.OperationActionResultEntity }
     * 
     */
    public CreateResponse.Return.OperationActionResultEntity createCreateResponseReturnOperationActionResultEntity() {
        return new CreateResponse.Return.OperationActionResultEntity();
    }

    /**
     * Create an instance of {@link CreateResponse.Return.ResponseInfo }
     * 
     */
    public CreateResponse.Return.ResponseInfo createCreateResponseReturnResponseInfo() {
        return new CreateResponse.Return.ResponseInfo();
    }

    /**
     * Create an instance of {@link CreateRequest.Request.RequestInfo }
     * 
     */
    public CreateRequest.Request.RequestInfo createCreateRequestRequestRequestInfo() {
        return new CreateRequest.Request.RequestInfo();
    }

    /**
     * Create an instance of {@link CreateRequest.Request.OperationEntity.Client }
     * 
     */
    public CreateRequest.Request.OperationEntity.Client createCreateRequestRequestOperationEntityClient() {
        return new CreateRequest.Request.OperationEntity.Client();
    }

    /**
     * Create an instance of {@link CreateRequest.Request.OperationEntity.ProxyClient }
     * 
     */
    public CreateRequest.Request.OperationEntity.ProxyClient createCreateRequestRequestOperationEntityProxyClient() {
        return new CreateRequest.Request.OperationEntity.ProxyClient();
    }

    /**
     * Create an instance of {@link CreateRequest.Request.OperationEntity.Documents.CreditAccountEntity }
     * 
     */
    public CreateRequest.Request.OperationEntity.Documents.CreditAccountEntity createCreateRequestRequestOperationEntityDocumentsCreditAccountEntity() {
        return new CreateRequest.Request.OperationEntity.Documents.CreditAccountEntity();
    }

    /**
     * Create an instance of {@link CreateRequest.Request.OperationEntity.Documents.CreditSumma }
     * 
     */
    public CreateRequest.Request.OperationEntity.Documents.CreditSumma createCreateRequestRequestOperationEntityDocumentsCreditSumma() {
        return new CreateRequest.Request.OperationEntity.Documents.CreditSumma();
    }

    /**
     * Create an instance of {@link CreateRequest.Request.OperationEntity.Documents.DebitAccountEntity }
     * 
     */
    public CreateRequest.Request.OperationEntity.Documents.DebitAccountEntity createCreateRequestRequestOperationEntityDocumentsDebitAccountEntity() {
        return new CreateRequest.Request.OperationEntity.Documents.DebitAccountEntity();
    }

    /**
     * Create an instance of {@link CreateRequest.Request.OperationEntity.Documents.DebitSumma }
     * 
     */
    public CreateRequest.Request.OperationEntity.Documents.DebitSumma createCreateRequestRequestOperationEntityDocumentsDebitSumma() {
        return new CreateRequest.Request.OperationEntity.Documents.DebitSumma();
    }

    /**
     * Create an instance of {@link CreateRequest.Request.OperationEntity.Documents.CashSymbols.Summa }
     * 
     */
    public CreateRequest.Request.OperationEntity.Documents.CashSymbols.Summa createCreateRequestRequestOperationEntityDocumentsCashSymbolsSumma() {
        return new CreateRequest.Request.OperationEntity.Documents.CashSymbols.Summa();
    }

}
